# CI de Nível 03 - Disparo automático sempre que outro for concluído, como ex. deploy
# nome que vai aparecer no github
name: 'Execucao por Deploy'
# triggers ou gatilhos de execucao
# Gatilho de execução por deploy após outro workflow executado = workflow_run
on:
  workflow_run:
    workflows: ['Execucao Manual']
    types:
      - completed

jobs:
  e2e-tests:
    # maquina que vai rodar
    runs-on: ['ubuntu-latest']

    # passo a paso das acoes do job
    steps:
      # - run: echo 'Execucao manual'
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      # - uses: actions/setup-node@v4
      #     with:
      #         node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install --with-deps

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
